language: bash

services:
  - docker

before_install:
  - docker run -it --rm --env WORDPRESS_DB_NAME=anteverse --volumes-from some-wordpress --network container:some-wordpress wordpress:cli user list

script:
  - bash check_wordpress_spam
